### ISSUE TITLE
[Feature Request] APU model name support

### ISSUE THREAD

**Issue by fagianijunior** [mark9064/pyamdgpuinfo#2]
Hello,
I am using you lib, and for dedicated GPU its show the model name, but, with a APU the model name is not showing.
With GPU the VRAM, temperature and model name is OK 
With APU the VRAM and temperature (same as the CPU) is showing OK, model name not.

Thank you,

**Comment by mark9064** [comment]
Yeah, this is something I also noticed. It comes from the amdgpu libdrm not reporting a marketing name for the device [function docs](https://gitlab.freedesktop.org/mesa/drm/-/blob/master/amdgpu/amdgpu.h#L1464). From my research, this resolves device IDs from [this list](https://gitlab.freedesktop.org/mesa/drm/-/blob/master/data/amdgpu.ids) and the APU IDs are for whatever reason not located here. I don't know if it is intentional or if AMD has forgotten to add them, but either way it's a problem that I can't really solve here.

I could try looking up the PCI IDs through `/usr/share/misc/pci.ids`, though I don't know how portable that is.

**Comment by mark9064** [comment]
As an update, I've opened an [issue in libdrm](https://gitlab.freedesktop.org/mesa/drm/-/issues/49) so hopefully this will be fixed soon.

**Comment by mark9064** [comment]
This has been [fixed in lidrm](https://gitlab.freedesktop.org/mesa/drm/-/merge_requests/89)
